### ISSUE TITLE
Apostrophes in attributes

### ISSUE THREAD

**Issue by codefucker** [Moveo/minimize#40]
Attribute 
```<div data-vars='{"form": "blablabla"}'></div>```
after processing will come to
```<div data-vars="{"form": "blablabla"}"></div>```

**Comment by Swaagie** [comment]
Currently this is not supported, since htmlparser2 will just parse out the content of the attribute and minimize reconstructs each attribute through https://github.com/Moveo/minimize/blob/master/lib/helpers.js#L72-L74, would an quoting style option be sufficient in this case? e.g. `new Minimize({ quotemarks: "'" })` where " is default and it can be optional set to '

**Comment by Swaagie** [comment]
Hmm perhaps a options named singlequote would make more sense, e.g. `new Minimize({ singlequote: true })` which would use a ' style

**Comment by codefucker** [comment]
I'm think second embodiment have more sense.

**Comment by codefucker** [comment]
Or can do a background check on the content attribute presence "

**Comment by Swaagie** [comment]
Good last call, will do that :) expect a patch release today
